// Categories of weapon types
CTI_WEAP_ARRAY_LIST=[ "ATGM" , "A2AM" , "ROCKETS" , "BOMBS" ];

CTI_WEAP_ATGM_INDEX=0;
CTI_WEAP_A2AM_INDEX=1;
CTI_WEAP_ROCKETS_INDEX=2;
CTI_WEAP_BOMBS_INDEX=3;

// Buy menu Icon IDC's
CTI_WEAP_ATGM_IDC=110110;
CTI_WEAP_A2AM_IDC=110111;
CTI_WEAP_ROCKETS_IDC=110112;
CTI_WEAP_BOMBS_IDC=110113;

// Buy lock icon IDC's
CTI_WEAP_ATGM_RESEARCH_LOCKED_IDC=110210;
CTI_WEAP_A2AM_RESEARCH_LOCKED_IDC=110211;
CTI_WEAP_ROCKETS_RESEARCH_LOCKED_IDC=110212;
CTI_WEAP_BOMBS_RESEARCH_LOCKED_IDC=110213;


// Cost scaling values
CTI_WEAP_ATGM_COSTSCALE = 2.5;
CTI_WEAP_A2AM_COSTSCALE = 0.85;
CTI_WEAP_ROCKETS_COSTSCALE = 0.35;
CTI_WEAP_BOMBS_COSTSCALE = 1.25;

// Magazine types for each weapon category
CTI_ATGM_BASED_MAGAZINES = [ "6Rnd_Missile_AGM_02_F" , "24Rnd_PG_missiles" , "12Rnd_PG_missiles" , "8Rnd_LG_scalpel" , "4Rnd_Missile_AGM_01_F" , "6Rnd_LG_scalpel" ];
CTI_A2AM_BASED_MAGAZINES = [ "2Rnd_Missile_AA_03_F" , "4Rnd_AAA_missiles" , "2Rnd_Missile_AA_04_F" ];
CTI_ROCKETS_BASED_MAGAZINES = [ "7Rnd_Rocket_04_HE_F" , "7Rnd_Rocket_04_AP_F" , "38Rnd_80mm_rockets" , "20Rnd_Rocket_03_HE_F" , "20Rnd_Rocket_03_AP_F" ,"24Rnd_missiles" ];
CTI_BOMBS_BASED_MAGAZINES = [ "4Rnd_Bomb_04_F" , "2Rnd_Bomb_03_F" , "2Rnd_GBU12_LGB" ];
